# Generated by Django 5.2.7 on 2025-10-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='Guest', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.order'),
        ),
    ]
